### ISSUE TITLE
Feedback/suggestion

### ISSUE THREAD

**Issue by xzonix** [is-cool-me/register#148]
### What do you want added?
Hello! A few days ago, in is-a.dev, a week ago, a lot of people started receiving phishing emails, and it was caused because on the JSON files, there was an email form to fill, and some guys scrapped all the emails from there. I think the email type can be replaced with Discord just to prevent phishing.

**Comment by LightHostingFree** [comment]
> ### What do you want added?
> Hello! A few days ago, in is-a.dev, a week ago, a lot of people started receiving phishing emails, and it was caused because on the JSON files, there was an email form to fill, and some guys scrapped all the emails from there. I think the email type can be replaced with Discord just to prevent phishing.

I think you have to open this issue in `https://github.com/is-a-dev/register` not here

**Comment by xzonix** [comment]
Bro im suggesting to remove the email form 💀

**Comment by xzonix** [comment]
"I think the email type can be replaced with Discord"

**Comment by LightHostingFree** [comment]
> "I think the email type can be replaced with Discord"

What if somebody does not use discord?

**Comment by LightHostingFree** [comment]
I think now I have to fully change storage system to private. But because of this manual registration will get stopped

**Comment by LightHostingFree** [comment]
I will migrate it when i get time
