### ISSUE TITLE
Domain is still pointing somewhere else

### ISSUE THREAD

**Issue by akpi816218** [is-cool-me/register#38]
I configured my subdomain `leafyleaf.is-cool.me` with a `CNAME` record to point to a GitHub Pages site in #33 a couple of days ago, but it's still pointing somewhere else. Running a [DNS check](https://www.whatsmydns.net/#CNAME/leafyleaf.is-cool.me) returns these `A` records but no `CNAME`.

`dig` output:
```shell
$ dig leafyleaf.is-cool.me +nostats +nocomments +nocmd
;leafyleaf.is-cool.me.          IN      A
leafyleaf.is-cool.me.   300     IN      A       104.21.14.153
leafyleaf.is-cool.me.   300     IN      A       172.67.203.192
```

**Comment by LightHostingFree** [comment]
You can check now I think it was the problem with proxy

**Comment by LightHostingFree** [comment]
> I configured my subdomain `leafyleaf.is-cool.me` with a `CNAME` record to point to a GitHub Pages site in #33 a couple of days ago, but it's still pointing somewhere else. Running a [DNS check](https://www.whatsmydns.net/#CNAME/leafyleaf.is-cool.me) returns these `A` records but no `CNAME`.
> 
> `dig` output:
> 
> ```shell
> $ dig leafyleaf.is-cool.me +nostats +nocomments +nocmd
> ;leafyleaf.is-cool.me.          IN      A
> leafyleaf.is-cool.me.   300     IN      A       104.21.14.153
> leafyleaf.is-cool.me.   300     IN      A       172.67.203.192
> ```

@akpi816218 You can check now I think it was the problem with proxy

**Comment by LightHostingFree** [comment]
`$ dig leafyleaf.is-cool.me +nostats +nocomments +nocmd
;leafyleaf.is-cool.me.          IN      A
leafyleaf.is-cool.me.   300     IN      CNAME   akpi816218.github.io.
akpi816218.github.io.   3600    IN      A       185.199.108.153
akpi816218.github.io.   3600    IN      A       185.199.111.153
akpi816218.github.io.   3600    IN      A       185.199.110.153
akpi816218.github.io.   3600    IN      A       185.199.109.153`

**Comment by akpi816218** [comment]
That looks great! Let me just fix something on GitHub Pages and I'll report back.

**Comment by akpi816218** [comment]
@LightHostingFree everything's fine now, thanks for your help! closing this issue.
