### ISSUE TITLE
Certificate?

### ISSUE THREAD

**Issue by RyanisyydsTT** [is-cool-me/register#42]
Hmm, certificate is gone

**Comment by LightHostingFree** [comment]
> Hmm, certificate is gone

What can you explain your question.
If you are saying that your domain doesn't have ssl so you have to get one from let's encrypt or zero ssl or **Turn on the proxy to true to get certificate from cloudflare**

**Comment by LightHostingFree** [comment]
@RyanisyydsTT BTW where do you got the vps

**Comment by RyanisyydsTT** [comment]
I don’t actually have a VPS
But I bought a hosting

**Comment by LightHostingFree** [comment]
> I don’t actually have a VPS But I bought a hosting

@RyanisyydsTT ok but what issue you are having with certificate?

**Comment by RyanisyydsTT** [comment]
I mean that, is the certificate built-in?

**Comment by LightHostingFree** [comment]
> I mean that, is the certificate built-in?

No but you can get it by a Hosting provider or by enabling proxy

**Comment by LightHostingFree** [comment]
@RyanisyydsTT please considering close this issue if your issue was solved
