### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by wdhdev** [is-cool-me/register#5]
Hi, I'm the owner of [Free Domains](https://github.com/free-domains/register) and an administrator of [Open Domains](https://github.com/open-domains/register), I see you have copied our CLI and register repo code.

We would appreciate if you would provide credit in the README of both the CLI and register repositories.

**Comment by LightHostingFree** [comment]
> Hi, I'm the owner of [Free Domains](https://github.com/free-domains/register) and an administrator of [Open Domains](https://github.com/open-domains/register), I see you have copied our CLI and register repo code.
> 
> We would appreciate if you would provide credit in the README of both the CLI and register repositories.

Done you can check.

**Comment by LightHostingFree** [comment]
> Hi, I'm the owner of [Free Domains](https://github.com/free-domains/register) and an administrator of [Open Domains](https://github.com/open-domains/register), I see you have copied our CLI and register repo code.
> 
> We would appreciate if you would provide credit in the README of both the CLI and register repositories.

Done you can check.

**Comment by wdhdev** [comment]
Thank you for your quick cooperation, have a great day :)
